"""Initial Migration

Revision ID: bbc4294c3088
Revises: f3bf3baf51a9
Create Date: 2019-09-17 22:44:31.721643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc4294c3088'
down_revision = 'f3bf3baf51a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_comment', sa.Text(), nullable=False))
    op.drop_column('comment', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('comment', 'user_comment')
    # ### end Alembic commands ###
